### PR TITLE
WIP: fix #15 add composer cache and refactor travis

### LINKED ISSUE #15: Travis Composer Download Cache
### Pacifica Search version
master
### Pacifica Core Software versions
master
### Platform Details
Travis
### Scenario:
The travis jobs are taking a while and we aren't even testing anything. The commands that are long are downloading stuff from the internet. 

https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/

### Steps to Reproduce:
1. Open a pull request
1. Watch travis for errors
### Expected Result:
Should be downloading composer cached dist files to install.
### Actual Result:
the composer install takes 400+ seconds...

### PR DESCRIPTION
**Pull request by dmlb2000**
### Description

This adds a generic cache directory to travis yaml to hopefully cache the composer files dir
### Issues Resolved

#15 
### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

File: travis/script.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#!/bin/bash -xe
+
+if [[ $LINTS == true ]] ; then
+  pre-commit run -a
+else
+  if [[ $RELEASE == dev ]]; then
+    composer --verbose remove --no-update drupal/console
+    composer --verbose require --no-update drupal/core:8.4.x-dev drush/drush:9.0.x-dev
```
Comment (thomscode) [inline travis/script.sh]: This line should be removed or commented as we aren't doing drupal core development

**Review by thomscode — CHANGES_REQUESTED** [review]

File: travis/script.sh (hunk 1 above)
Comment (dmlb2000) [reply travis/script.sh]: This is under the `RELEASE=dev` environment variable which isn't being set... so this is never being hit... I'd like to keep it as it's a way of getting a pre-release of drupal to test against (just in case) so I'll comment it out with the note for now

**Comment by dmlb2000** [comment]
Okay, so in the (right now) web directory where would the code you write go to perform php tests?

**Review by thomscode — APPROVED** [review]

**Comment by thomscode** [comment]
@dmlb2000 
I submitted an "approved" review, but as I don't have write access to the repository, it's still showing as blocked.
